### ISSUE TITLE
Document features & add screenshots

### ISSUE THREAD

**Issue by alexanderadam** [jonashellmann/everydocs-core#7]
Hi Jonas,

it would be great if you would add some screenshots and the currently implemented features to the readme or a GitHub page or something like that.

This would make it easier to get an impression of everydocs.

Thank you for your work!

**Comment by jonashellmann** [comment]
Hi Alexander,

thank you very much for the suggestion, I appreciate it!
I just added a list of features and two screenshots of the web interface to the README. 😄

**Comment by alexanderadam** [comment]
Ah, is there any plan what features you are planning to implement?
Is there support for versioned documents or custom attributes on documents?

**Comment by jonashellmann** [comment]
At the moment, there are no concrete plans for the future and I am currently somewhat limited in time due to my bachelor thesis and work. In principle, I would like to develop a mobile app, but that will be very time-consuming.
I think versioned documents are a very good idea! And tags are already supported, at least in theory, but I haven't implemented them anywhere in the web interface yet. If you feel like it, you can also see if you want to contribute something to this project, I would always be open for that. Otherwise I'll have to see when I get around to it. :-)

**Comment by alexanderadam** [comment]
I see. I evaluated some solutions and stumbled over everydocs
We like the stack but the missing features probably won't be enough to compete (at least at the moment).

> I am currently somewhat limited in time due to my bachelor thesis and work.

No worries. Work on FOSS tools should be fun and never cause pressure. So concentrate on your thesis, work and your health.

> tags are already supported

Tags are great but I asked for custom attributes. :wink: 
Usually DMS allow you to add some custom attributes (i.e. `some_foreign_user_id`) with some validated meta information (i.e. the field must be an integer and must be present for this document type).

> you can also see if you want to contribute something to this project,

We would've probably done that if the base requirements would've been fulfilled already.

I'm very sorry that I don't have any better news. Everydocs might not be there yet but it seems to be on a very good way. :+1:
